# This is a basic workflow to help you get started with Actions

name: CI/CD - HML

on:
  push:
    branches: [ release ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_HML }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          branch: "release"
